In [1]:
# pip install BigQuery

Authentication to retrieve Dataset

In [2]:
from google.colab import auth

In [3]:
auth.authenticate_user()

In [4]:
from google.cloud import bigquery as bq

Step 1: Create Client object

**Client** objects hold projects and a connection to the BigQuery service

In [5]:
client = bq.Client()

Step 2: Use DatasetReference("project", "dataset_id)

Project: Collection of datasets

dataset: Collection of tables

In [6]:
dataset_ref = bq.DatasetReference("bigquery-public-data", "hacker_news")

Step 3: Use get_dataset() to fetch data

In [7]:
dataset = client.get_dataset(dataset_ref)

Use list_tables() to list the tables in dataset

In [8]:
# List all the tables in the dataset
tables = list(client.list_tables(dataset))

In [9]:
# Print names of all tables in dataset
for table in tables:
  print(table.table_id)

full

Fetch a table from dataset (if there are multiple tables)

Use dataset_ref() for reference to the table

Use get_table() to fetch the table

In [10]:
# Construct a reference to the desired table
table_ref = dataset_ref.table("full")

In [11]:
# API call to fetch the table
table = client.get_table(table_ref)

In [12]:
print(table)

bigquery-public-data.hacker_news.full

# Table Schema

Schema: Structure of a table

Each SchemaField shows a specific column(field)

SchemaField('name', 'field type', 'mode (default:NULLABLE)', description of the data, ())

**NOTE:** Mode is by default NULLABLE. It means that a column allows NULL values.

In [13]:
# Print info on all the columns of the fetched table
table.schema

[SchemaField('title', 'STRING', 'NULLABLE', None, 'Story title', (), None, None),
 SchemaField('url', 'STRING', 'NULLABLE', None, 'Story url', (), None, None),
 SchemaField('text', 'STRING', 'NULLABLE', None, 'Story or comment text', (), None, None),
 SchemaField('dead', 'BOOLEAN', 'NULLABLE', None, 'Is dead?', (), None, None),
 SchemaField('by', 'STRING', 'NULLABLE', None, "The username of the item's author.", (), None, None),
 SchemaField('score', 'INTEGER', 'NULLABLE', None, 'Story score', (), None, None),
 SchemaField('time', 'INTEGER', 'NULLABLE', None, 'Unix time', (), None, None),
 SchemaField('timestamp', 'TIMESTAMP', 'NULLABLE', None, 'Timestamp for the unix time', (), None, None),
 SchemaField('type', 'STRING', 'NULLABLE', None, 'type of details (comment comment_ranking poll story job pollopt)', (), None, None),
 SchemaField('id', 'INTEGER', 'NULLABLE', None, "The item's unique id.", (), None, None),
 SchemaField('parent', 'INTEGER', 'NULLABLE', None, 'Parent comment ID', (), None, None),
 SchemaField('descendants', 'INTEGER', 'NULLABLE', None, 'Number of story or poll descendants', (), None, None),
 SchemaField('ranking', 'INTEGER', 'NULLABLE', None, 'Comment ranking', (), None, None),
 SchemaField('deleted', 'BOOLEAN', 'NULLABLE', None, 'Is deleted?', (), None, None)]

**Preview** Some Table Data

Use list_rows(table_name, max_results)

In [15]:
# Preview the first five lines of the table
client.list_rows(table, max_results=50).to_dataframe()

,title,url,text,dead,by,score,time,timestamp,type,id,parent,descendants,ranking,deleted
0,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944309,<NA>,<NA>,<NA>,<NA>
1,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944322,<NA>,<NA>,<NA>,<NA>
2,None,None,None,<NA>,None,<NA>,1437764061,2015-07-24 18:54:21+00:00,story,9944325,<NA>,<NA>,<NA>,<NA>
3,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944348,<NA>,<NA>,<NA>,<NA>
4,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944354,<NA>,<NA>,<NA>,<NA>
5,None,None,None,<NA>,None,<NA>,1437764596,2015-07-24 19:03:16+00:00,story,9944373,<NA>,<NA>,<NA>,<NA>
6,None,None,None,<NA>,None,<NA>,1437764729,2015-07-24 19:05:29+00:00,story,9944389,<NA>,<NA>,<NA>,<NA>
7,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944476,<NA>,<NA>,<NA>,<NA>
8,None,None,None,<NA>,None,<NA>,1437765836,2015-07-24 19:23:56+00:00,story,9944527,<NA>,<NA>,<NA>,<NA>
9,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944533,<NA>,<NA>,<NA>,<NA>
10,None,None,None,<NA>,None,<NA>,1437766078,2015-07-24 19:27:58+00:00,story,9944558,<NA>,<NA>,<NA>,<NA>
11,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944666,<NA>,<NA>,<NA>,<NA>
12,None,None,None,<NA>,None,<NA>,1437767743,2015-07-24 19:55:43+00:00,story,9944742,<NA>,<NA>,<NA>,<NA>
13,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944752,<NA>,<NA>,<NA>,<NA>
14,None,None,None,<NA>,None,<NA>,1437768124,2015-07-24 20:02:04+00:00,story,9944792,<NA>,<NA>,<NA>,<NA>
15,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944807,<NA>,<NA>,<NA>,<NA>
16,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944858,<NA>,<NA>,<NA>,<NA>
17,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944864,<NA>,<NA>,<NA>,<NA>
18,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944872,<NA>,<NA>,<NA>,<NA>
19,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944877,<NA>,<NA>,<NA>,<NA>
20,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944888,<NA>,<NA>,<NA>,<NA>
21,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944895,<NA>,<NA>,<NA>,<NA>
22,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944901,<NA>,<NA>,<NA>,<NA>
23,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,9944905,<NA>,<NA>,<NA>,<NA>
24,None,None,None,<NA>,None,<NA>,1437769276,2015-07-24 20:21:16+00:00,story,9944927,<NA>,<NA>,<NA>,<NA>
25,None,None,None,<NA>,None,<NA>,1437769313,2015-07-24 20:21:53+00:00,story,9944932,<NA>,<NA>,<NA>,<NA>
26,None,None,None,<NA>,None,<NA>,1260810947,2009-12-14 17:15:47+00:00,story,994509,<NA>,<NA>,<NA>,<NA>
27,None,None,None,<NA>,None,<NA>,1437773037,2015-07-24 21:23:57+00:00,story,9945282,<NA>,<NA>,<NA>,<NA>
28,None,None,None,<NA>,None,<NA>,1437779677,2015-07-24 23:14:37+00:00,story,9945806,<NA>,<NA>,<NA>,<NA>
29,None,None,None,<NA>,None,<NA>,1437782037,2015-07-24 23:53:57+00:00,story,9945926,<NA>,<NA>,<NA>,<NA>
30,None,None,None,<NA>,None,<NA>,1437783176,2015-07-25 00:12:56+00:00,story,9945992,<NA>,<NA>,<NA>,<NA>
31,None,None,None,<NA>,None,<NA>,1437783795,2015-07-25 00:23:15+00:00,story,9946018,<NA>,<NA>,<NA>,<NA>
32,None,None,None,<NA>,None,<NA>,1437784053,2015-07-25 00:27:33+00:00,story,9946026,<NA>,<NA>,<NA>,<NA>
33,None,None,None,<NA>,None,<NA>,1437786155,2015-07-25 01:02:35+00:00,story,9946152,<NA>,<NA>,<NA>,<NA>
34,None,None,None,<NA>,None,<NA>,1437787040,2015-07-25 01:17:20+00:00,story,9946185,<NA>,<NA>,<NA>,<NA>
35,None,None,None,<NA>,None,<NA>,1437795554,2015-07-25 03:39:14+00:00,story,9946452,<NA>,<NA>,<NA>,<NA>
36,None,None,None,<NA>,None,<NA>,1437797077,2015-07-25 04:04:37+00:00,story,9946502,<NA>,<NA>,<NA>,<NA>
37,None,None,None,<NA>,None,<NA>,1200521045,2008-01-16 22:04:05+00:00,story,99467,<NA>,<NA>,<NA>,<NA>
38,None,None,None,<NA>,None,<NA>,1437815597,2015-07-25 09:13:17+00:00,story,9947071,<NA>,<NA>,<NA>,<NA>
39,None,None,None,<NA>,None,<NA>,1437815637,2015-07-25 09:13:57+00:00,story,9947075,<NA>,<NA>,<NA>,<NA>
40,None,None,None,<NA>,None,<NA>,1437816409,2015-07-25 09:26:49+00:00,story,9947092,<NA>,<NA>,<NA>,<NA>
41,None,None,None,<NA>,None,<NA>,<NA>,NaT,story,99472,<NA>,<NA>,<NA>,<NA>
42,None,None,None,<NA>,None,<NA>,1437821924,2015-07-25 10:58:44+00:00,story,9947209,<NA>,<NA>,<NA>,<NA>
43,None,None,None,<NA>,None,<NA>,1437823163,2015-07-25 11:19:23+00:00,story,9947247,<NA>,<NA>,<NA>,<NA>
44,None,None,None,<NA>,None,<NA>,1437826008,2015-07-25 12:06:48+00:00,story,9947345,<NA>,<NA>,<NA>,<NA>
45,None,None,None,<NA>,None,<NA>,1437828196,2015-07-25 12:43:16+00:00,job,9947426,<NA>,<NA>,<NA>,<NA>
46,None,None,None,<NA>,None,<NA>,1437832734,2015-07-25 13:58:54+00:00,story,9947584,<NA>,<NA>,<NA>,<NA>
47,None,None,None,True,None,<NA>,1437837121,2015-07-25 15:12:01+00:00,story,9947778,<NA>,<NA>,<NA>,<NA>
48,None,None,None,<NA>,None,<NA>,1437839510,2015-07-25 15:51:50+00:00,story,9947911,<NA>,<NA>,<NA>,<NA>
49,None,None,None,<NA>,None,<NA>,1437839617,2015-07-25 15:53:37+00:00,story,9947918,<NA>,<NA>,<NA>,<NA>

In [16]:
# Preview the Fist five entries in the specific column of the table
client.list_rows(table, selected_fields=table.schema[:1], max_results=5).to_dataframe()

  title
0  None
1  None
2  None
3  None
4  None

In [19]:
client.list_rows(table, selected_fields=table.schema[:4], max_results=5).to_dataframe()

  title   url  text  dead
0  None  None  None  <NA>
1  None  None  None  <NA>
2  None  None  None  <NA>
3  None  None  None  <NA>
4  None  None  None  <NA>